// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

import { implicitReturnType } from '../base/types.js';
import { Exchange as _Exchange } from '../base/Exchange.js';

interface Exchange {
    publicGetMarkets (params?: {}): Promise<implicitReturnType>;
    publicGetMarket (params?: {}): Promise<implicitReturnType>;
    publicGetAllMids (params?: {}): Promise<implicitReturnType>;
    publicGetSpotAssetCtx (params?: {}): Promise<implicitReturnType>;
    publicGetPerpAssetCtx (params?: {}): Promise<implicitReturnType>;
    publicGetL2book (params?: {}): Promise<implicitReturnType>;
    publicGetRecentMarketTrades (params?: {}): Promise<implicitReturnType>;
    publicGetCandles (params?: {}): Promise<implicitReturnType>;
    publicGetAccountId (params?: {}): Promise<implicitReturnType>;
    publicGetOrder (params?: {}): Promise<implicitReturnType>;
    publicGetOpenOrders (params?: {}): Promise<implicitReturnType>;
    publicGetHistoricalOrders (params?: {}): Promise<implicitReturnType>;
    publicGetSpotState (params?: {}): Promise<implicitReturnType>;
    publicGetClearinghouseState (params?: {}): Promise<implicitReturnType>;
    publicGetAllClearinghouseState (params?: {}): Promise<implicitReturnType>;
    publicGetUserFees (params?: {}): Promise<implicitReturnType>;
    publicGetUserFundingHistory (params?: {}): Promise<implicitReturnType>;
    publicGetUserTrades (params?: {}): Promise<implicitReturnType>;
}
abstract class Exchange extends _Exchange {}

export default Exchange
